name: crypto_assessment
description: "PulseNow Flutter Developer Assessment - Market Data App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  dart_kit:
    path: packages/dart_kit

  # UI
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  
  # State Management
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  
  # Dependency Injection
  injectable: ^2.4.4
  get_it: ^8.0.3
  
  # Networking
  dio: ^5.8.0+1
  http: ^1.4.0
  
  # Code Generation
  freezed_annotation: ^2.4.4
  json_annotation: 4.9.0
  
  # Utilities
  dartz: ^0.10.1
  logger: ^1.1.0
  intl: ^0.20.2
  web_socket_channel: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true


